# Generated by Django 5.1.1 on 2024-10-27 15:31

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
    ]
