# Generated by Django 5.1.1 on 2024-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
